steps:
- id: 'e2e-test'
  waitFor: ['-']
  name: "gcr.io/cloud-builders/gcloud"
  dir: '${_SAMPLE_DIR}'
  script: |
    #!/bin/bash
    ./tests/e2e-test.sh || touch /workspace/e2e-failed
  env:
    - '_REGION=$_REGION'    
    - '_SERVICE_NAME=$_SERVICE_NAME'
- id: 'e2e-cleanup'
  waitFor: ['e2e-test']
  name: "gcr.io/cloud-builders/gcloud"
  dir: '${_SAMPLE_DIR}'
  entrypoint: './tests/e2e-cleanup.sh'
  env:
    - '_REGION=$_REGION'    
    - '_SERVICE_NAME=$_SERVICE_NAME'
- id: 'report-status'
  waitFor: ['e2e-cleanup']
  name: "gcr.io/cloud-builders/gcloud"
  dir: '${_SAMPLE_DIR}'
  script: |
    #!/bin/bash
    if [[ -f /workspace/e2e-failed   ]]
    then
      echo "Step e2e-test failed"
      exit 1
    fi 
substitutions:  
  _SERVICE_NAME: 'nginx-example'
  _REGION: 'us-central1'
  _SAMPLE_DIR: 'multi-container/hello-nginx-sample'
