steps:
- id: 'Lint Dockerfile'
  name: 'hadolint/hadolint:latest-debian'
  entrypoint: '/bin/bash'
  args:
  - -c
  - | # Recursively find dockerfiles (not in testing dir)
    for f in $(find . -name '*Dockerfile' -not -path "./testing/*")
      do hadolint $f
    done
