steps:
- id: 'Lint Shell'
  name: 'koalaman/shellcheck-alpine' # https://hub.docker.com/r/koalaman/shellcheck-alpine/
  entrypoint: '/bin/sh'
  args:
  - -c
  - | # Recursively find shell scripts (not in testing dir)
    function catchError {
      shellcheck -f gcc $1;
      shellcheck -f gcc $1 | grep -q "error"
      if [[ $? -eq 0 ]]; then echo "fail" > ./build-status.txt ; fi
    }
    find . -name '*.sh' -not -path "./testing/*" -exec sh -c 'catchError {}' \;
