# [START run_yaml_limits_cpu]
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: SERVICE
spec:
  template:
    spec:
      containers:
      - image: IMAGE
        resources:
          limits:
            cpu: 'CPU'
# [END run_yaml_limits_cpu]
