steps:

- id: 'Build Container Image'
  name: 'gcr.io/cloud-builders/docker:latest'
  dir: '${_SAMPLE_DIR}'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA}', '.'] # Tag docker image with git commit sha

- id: 'Push Container Image'
  name: 'gcr.io/cloud-builders/docker:latest'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA}']

- id: 'Deploy to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  entrypoint: /bin/bash
  args:
  - '-c'
  - | # Cloud Run Service name must be less than 63 characters
    cat /dev/urandom | LC_CTYPE=C tr -dc 'a-z0-9' | head -c 15 > _short_id # Generate a random 15 character alphanumeric string (lowercase only)
    gcloud run deploy ${_SERVICE}-$(cat _short_id) \
     --image gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA} \
     --no-allow-unauthenticated \
     --region ${_SERVICE_REGION} \
     --platform managed

- id: 'Get Cloud Run URL'
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    get_url() {
        gcloud run services describe ${_SERVICE}-$(cat _short_id) --format 'value(status.url)' \
          --platform managed --region ${_SERVICE_REGION}
    }
    echo $(get_url) > _service_url
    echo "Cloud Run URL for ${_SERVICE}-$(cat _short_id) is $(cat _service_url)"

- id: 'Integration Tests'
  # TODO: Update the following image name, entrypoint, and args to fit your testing needs
  name: 'alpine:3'
  entrypoint: '/bin/sh'
  dir: '${_SAMPLE_DIR}'
  args:
  - '-c'
  - |
    echo "Add integration tests!"

- id: 'Teardown'
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    set -x
    gcloud --quiet container images delete gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA}
    gcloud --quiet run services delete ${_SERVICE}-$(cat _short_id) --region ${_SERVICE_REGION} --platform managed
    set +x
    echo "View build details in the console: https://console.cloud.google.com/cloud-build/builds/${BUILD_ID}"

# Uncomment if skipping teardown to associate build with container image.
# images:
# - 'gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA}'

# TODO: Update these User-defined substitutions
substitutions:
  _SERVICE: helloworld-shell
  _SAMPLE_DIR: helloworld-shell
  _SERVICE_REGION: us-central1
  _CLOUDSDK_VERSION: latest
