createTime: '2020-09-25T18:51:42.819473052Z'
description: pull-request
filename: vpc-sample/tests.cloudbuild.yaml
github:
  name: cloud-run-samples
  owner: GoogleCloudPlatform
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
id: b1ea04f0-d90b-4a69-a4ab-7fecff4c9705
includedFiles:
- vpc-sample/*
name: vpc-sample-pr
substitutions:
  _RUNNER_IDENTITY: test-runner-identity@cloud-run-samples-test.iam.gserviceaccount.com
  _SECRET_NAME: locksmith-secret